use_frameworks!

platform :ios, '9.0'

target 'LRSEntranceSourceLoader_Example' do
  pod 'LRSEntranceSourceLoader', :path => '../'

  target 'LRSEntranceSourceLoader_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
